const NODES = [
  // === DELIVERY STATIONS (D) - Exact from Bulk where possible, approximated otherwise ===
  {station:"DCT9",lat:41.39,lon:2.17,stores:0,provinces:["Barcelona"],region:"Cataluña",type:"DS"},
  {station:"DQB9",lat:38.84,lon:-3.44,stores:34,provinces:["Ciudad Real"],region:"Castilla-La Mancha",type:"DS"},
  {station:"DMA3",lat:40.42,lon:-3.70,stores:0,provinces:["Madrid"],region:"Madrid",type:"DS"},
  {station:"DQV6",lat:39.47,lon:-0.38,stores:0,provinces:["Valencia"],region:"C. Valenciana",type:"DS"},
  {station:"DAS1",lat:40.45,lon:-3.68,stores:0,provinces:["Madrid"],region:"Madrid",type:"DS"},
  {station:"DCT4",lat:41.12,lon:1.25,stores:0,provinces:["Tarragona"],region:"Cataluña",type:"DS"},
  {station:"DCT7",lat:41.98,lon:2.82,stores:0,provinces:["Girona"],region:"Cataluña",type:"DS"},
  {station:"DCZ3",lat:41.65,lon:-0.88,stores:0,provinces:["Zaragoza"],region:"Aragón",type:"DS"},
  {station:"DGA2",lat:37.18,lon:-3.60,stores:0,provinces:["Granada"],region:"Andalucía",type:"DS"},
  {station:"DQA4",lat:36.72,lon:-4.42,stores:0,provinces:["Málaga"],region:"Andalucía",type:"DS"},
  {station:"DQA3",lat:37.39,lon:-5.99,stores:0,provinces:["Sevilla"],region:"Andalucía",type:"DS"},
  {station:"DQV2",lat:38.66,lon:-0.89,stores:21,provinces:["Alicante","Valencia","Albacete"],region:"C. Valenciana",type:"DS"},
  {station:"DCZ4",lat:41.65,lon:-0.90,stores:0,provinces:["Zaragoza"],region:"Aragón",type:"DS"},
  {station:"DQM5",lat:36.72,lon:-4.43,stores:0,provinces:["Málaga"],region:"Andalucía",type:"DS"},
  {station:"DQB6",lat:43.14,lon:-2.54,stores:19,provinces:["Bizkaia","Gipuzkoa","Burgos"],region:"País Vasco",type:"DS"},
  {station:"DGA1",lat:37.13,lon:-2.64,stores:81,provinces:["Almería","Granada"],region:"Andalucía",type:"DS"},
  {station:"DZG2",lat:41.66,lon:-0.88,stores:0,provinces:["Zaragoza"],region:"Aragón",type:"DS"},
  {station:"DQB5",lat:43.26,lon:-2.93,stores:0,provinces:["Bizkaia"],region:"País Vasco",type:"DS"},
  {station:"DMZ2",lat:40.45,lon:-3.72,stores:0,provinces:["Madrid"],region:"Madrid",type:"DS"},
  {station:"DQB2",lat:42.59,lon:-8.79,stores:26,provinces:["Pontevedra","A Coruña"],region:"Galicia",type:"DS"},
  {station:"DQL2",lat:41.66,lon:-5.12,stores:9,provinces:["Zamora","Salamanca","Palencia"],region:"Castilla y León",type:"DS"},
  {station:"DIC1",lat:28.12,lon:-15.43,stores:0,provinces:["Las Palmas"],region:"Canarias",type:"DS"},
  {station:"DQA8",lat:37.88,lon:-4.78,stores:0,provinces:["Córdoba"],region:"Andalucía",type:"DS"},
  {station:"DMA4",lat:40.01,lon:-4.24,stores:61,provinces:["Ávila","Toledo","Madrid Oeste"],region:"Castilla y León",type:"DS"},
  {station:"DMA6",lat:40.63,lon:-3.16,stores:0,provinces:["Guadalajara","Madrid Norte"],region:"Madrid",type:"DS"},
  {station:"DQV8",lat:40.31,lon:-0.21,stores:31,provinces:["Castellón","Tarragona","Teruel"],region:"C. Valenciana",type:"DS"},
  {station:"DMZ4",lat:40.40,lon:-3.55,stores:0,provinces:["Madrid"],region:"Madrid",type:"DS"},
  {station:"DQA7",lat:36.69,lon:-5.80,stores:49,provinces:["Cádiz","Sevilla"],region:"Andalucía",type:"DS"},
  {station:"DGP1",lat:37.13,lon:-2.64,stores:81,provinces:["Almería","Granada"],region:"Andalucía",type:"DS"},
  {station:"DQE2",lat:39.00,lon:-6.11,stores:109,provinces:["Badajoz","Cáceres"],region:"Extremadura",type:"DS"},

  // === HUBS (O) - Operations with Delivery Partners ===
  {station:"OCM2",lat:40.38,lon:-3.75,stores:0,provinces:["Madrid"],region:"Madrid",type:"Hub"},
  {station:"OCM4",lat:40.48,lon:-3.58,stores:0,provinces:["Madrid"],region:"Madrid",type:"Hub"},
  {station:"OCB4",lat:41.42,lon:2.10,stores:0,provinces:["Barcelona"],region:"Cataluña",type:"Hub"},
  {station:"OCN1",lat:42.82,lon:-1.64,stores:0,provinces:["Navarra"],region:"Navarra",type:"Hub"},
  {station:"OQV7",lat:39.48,lon:-0.35,stores:0,provinces:["Valencia"],region:"C. Valenciana",type:"Hub"},
  {station:"OCL4",lat:42.35,lon:-3.70,stores:0,provinces:["Burgos"],region:"Castilla y León",type:"Hub"},
  {station:"OCL5",lat:42.60,lon:-5.57,stores:0,provinces:["León"],region:"Castilla y León",type:"Hub"},
  {station:"OCL2",lat:41.65,lon:-4.72,stores:0,provinces:["Valladolid"],region:"Castilla y León",type:"Hub"},
  {station:"OCL3",lat:40.96,lon:-5.66,stores:0,provinces:["Salamanca"],region:"Castilla y León",type:"Hub"},
  {station:"OML1",lat:40.42,lon:-3.68,stores:0,provinces:["Madrid"],region:"Madrid",type:"Hub"},
  {station:"OQA3",lat:37.39,lon:-5.98,stores:0,provinces:["Sevilla"],region:"Andalucía",type:"Hub"},
  {station:"OQA6",lat:36.72,lon:-4.42,stores:0,provinces:["Málaga"],region:"Andalucía",type:"Hub"},
  {station:"OGA5",lat:37.18,lon:-3.60,stores:0,provinces:["Granada"],region:"Andalucía",type:"Hub"},
  {station:"OQA4",lat:36.72,lon:-4.43,stores:0,provinces:["Málaga"],region:"Andalucía",type:"Hub"},
  {station:"OCM1",lat:40.33,lon:-3.77,stores:0,provinces:["Madrid Sur"],region:"Madrid",type:"Hub"},
  {station:"OCN2",lat:42.81,lon:-1.65,stores:0,provinces:["Navarra"],region:"Navarra",type:"Hub"},
  {station:"ORI2",lat:42.46,lon:-2.45,stores:0,provinces:["La Rioja"],region:"La Rioja",type:"Hub"},
];
