const QUESTIONS = [
  // === CATEGORÍA: Acrónimos Generales ===
  {cat:"Organización",q:"¿Qué significa AMZL?",a:"Amazon Logistics",opts:["Amazon Logistics","Amazon Last Zone","Amazon Load Management","Amazon Line"]},
  {cat:"Organización",q:"¿Qué es un HUB en AMZL?",a:"Centro de despacho de paquetes para última milla",opts:["Centro de despacho de paquetes para última milla","Almacén de devoluciones","Centro de clasificación regional","Oficina administrativa"]},
  {cat:"Organización",q:"¿Qué significa DBR?",a:"Daily Business Review",opts:["Daily Business Review","Data Base Report","Delivery Batch Record","Daily Batch Run"]},
  {cat:"Organización",q:"¿Qué es un DP (Delivery Partner)?",a:"Socio de entrega (DSP o Flex)",opts:["Socio de entrega (DSP o Flex)","Departamento de planificación","Data Point","Delivery Protocol"]},
  {cat:"Organización",q:"¿Qué significa DSP?",a:"Delivery Service Partner",opts:["Delivery Service Partner","Digital Service Platform","Daily Shipment Plan","Dispatch Service Protocol"]},
  {cat:"Organización",q:"¿Qué región es SEU?",a:"Southern Europe (Europa del Sur)",opts:["Southern Europe (Europa del Sur)","Southeast Union","Spain EU","South East Unit"]},
  {cat:"Organización",q:"¿Qué significa WW HDP?",a:"Worldwide Hub Delivery Program",opts:["Worldwide Hub Delivery Program","Weekly Warehouse Distribution Plan","World Wide High Demand Priority","Warehouse Hub Dispatch Protocol"]},

  // === CATEGORÍA: Planificación y Volumen (SnOP) ===
  {cat:"SnOP",q:"¿Qué significa SnOP?",a:"Sales and Operations Planning",opts:["Sales and Operations Planning","Station Network Operations","Supply and Order Processing","Shipment Notification Protocol"]},
  {cat:"SnOP",q:"¿Qué significa OFD?",a:"Out for Delivery (paquetes que salieron a reparto)",opts:["Out for Delivery (paquetes que salieron a reparto)","Order Fulfillment Date","Outbound Freight Dispatch","Overnight Fast Delivery"]},
  {cat:"SnOP",q:"¿Qué es Fcst?",a:"Forecast (Pronóstico de volumen)",opts:["Forecast (Pronóstico de volumen)","Fast count","Fulfillment cost","First class shipment time"]},
  {cat:"SnOP",q:"¿Qué significa D0?",a:"Day Zero (día actual/hoy)",opts:["Day Zero (día actual/hoy)","Delivery Zero defects","Dispatch Order","Default Origin"]},
  {cat:"SnOP",q:"¿Qué es W0/W1?",a:"Semana actual / Semana siguiente",opts:["Semana actual / Semana siguiente","Warehouse 0 / Warehouse 1","Wave 0 / Wave 1","Worker shift 0 / 1"]},
  {cat:"SnOP",q:"¿Qué mide Cap Utilization?",a:"Porcentaje de uso de la capacidad instalada de una estación",opts:["Porcentaje de uso de la capacidad instalada de una estación","Capacidad de los camiones","Capital utilizado en operaciones","Cantidad de personal activo"]},
  {cat:"SnOP",q:"¿Qué es New Intake?",a:"Volumen nuevo de paquetes que ingresa a la red logística",opts:["Volumen nuevo de paquetes que ingresa a la red logística","Nuevos empleados contratados","Nuevas rutas creadas","Nuevos DSPs incorporados"]},
  {cat:"SnOP",q:"¿Qué significa WtD?",a:"Week to Date (acumulado de la semana)",opts:["Week to Date (acumulado de la semana)","Warehouse to Delivery","Wait time Distribution","Weekly total Dispatched"]},
  {cat:"SnOP",q:"¿Qué es WON en attainment?",a:"Week Over Network (métrica semanal sobre la red)",opts:["Week Over Network (métrica semanal sobre la red)","Win Over Next","Warehouse Operations Number","Weekly Order Notification"]},
  {cat:"SnOP",q:"Si Cap Utilization D0 es 94.08%, ¿qué significa?",a:"Las estaciones están usando el 94% de su capacidad hoy",opts:["Las estaciones están usando el 94% de su capacidad hoy","Se entregó el 94% de los paquetes","El 94% del personal asistió","El forecast fue 94% preciso"]},
  {cat:"SnOP",q:"¿Cuántas estaciones están en riesgo si Cap Util > 98% = 154?",a:"154 estaciones están cerca de saturarse",opts:["154 estaciones están cerca de saturarse","154 paquetes están en riesgo","154 rutas están llenas","154 DSPs están al máximo"]},

  // === CATEGORÍA: Calidad y Experiencia (LMDX) ===
  {cat:"LMDX",q:"¿Qué significa LMDX?",a:"Last Mile Delivery Experience",opts:["Last Mile Delivery Experience","Logistics Management Data Exchange","Load Management Dispatch","Last Mile Distribution Index"]},
  {cat:"LMDX",q:"¿Qué es un BPS (Basis Point)?",a:"1 BPS = 0.01%, mide impacto en coste",opts:["1 BPS = 0.01%, mide impacto en coste","Batches Per Second","Business Performance Score","Bulk Package Shipment"]},
  {cat:"LMDX",q:"¿Qué mide DPMO?",a:"Defectos por millón de oportunidades",opts:["Defectos por millón de oportunidades","Deliveries Per Month","Daily Package Movement Output","Dispatch Priority Management Order"]},
  {cat:"LMDX",q:"¿Qué es PDD?",a:"Promised Delivery Date (fecha prometida al cliente)",opts:["Promised Delivery Date (fecha prometida al cliente)","Package Delivery Dispatch","Priority Delivery Day","Post-Delivery Data"]},
  {cat:"LMDX",q:"¿Qué significa DEA en LMDX?",a:"Delivery Execution Attempt (ventana de intento de entrega)",opts:["Delivery Execution Attempt (ventana de intento de entrega)","Daily Efficiency Analysis","Dispatch Error Alert","Delivery Exception Action"]},
  {cat:"LMDX",q:"¿Qué es NOV?",a:"Not on Van (paquete no cargado en la furgoneta)",opts:["Not on Van (paquete no cargado en la furgoneta)","Network Over Volume","Next Order Verification","No Operational Vehicle"]},
  {cat:"LMDX",q:"¿Qué significa OV?",a:"Over Volume (exceso de volumen sobre capacidad)",opts:["Over Volume (exceso de volumen sobre capacidad)","Order Verified","Outbound Vehicle","Operational Variance"]},
  {cat:"LMDX",q:"¿Qué es PANDA?",a:"Sistema interno que calcula el Attainment",opts:["Sistema interno que calcula el Attainment","Herramienta de tracking de paquetes","Sistema de nómina","App de comunicación interna"]},
  {cat:"LMDX",q:"¿Qué son Slow Connections (SC)?",a:"Conexiones lentas entre nodos de la red",opts:["Conexiones lentas entre nodos de la red","Estaciones pequeñas","Conductores lentos","Sistemas caídos"]},
  {cat:"LMDX",q:"¿Qué significa ATS?",a:"Available to Ship (disponible para envío)",opts:["Available to Ship (disponible para envío)","Automated Tracking System","Average Time to Sort","All Time Score"]},
  {cat:"LMDX",q:"Si First Day Delivery Success es 98.81%, ¿qué significa?",a:"El 98.81% de paquetes se entregó en el primer día prometido",opts:["El 98.81% de paquetes se entregó en el primer día prometido","El 98.81% de conductores completó su ruta","El 98.81% de estaciones operó sin problemas","El 98.81% de clientes respondió positivamente"]},
  {cat:"LMDX",q:"¿Qué mide Concession DPMO?",a:"Compensaciones al cliente por fallo, en defectos por millón",opts:["Compensaciones al cliente por fallo, en defectos por millón","Concesiones de espacio en almacén","Descuentos a DSPs","Permisos de estacionamiento"]},

  // === CATEGORÍA: Seguridad ===
  {cat:"Seguridad",q:"¿Qué significa XSI?",a:"Community Member Serious Incident",opts:["Community Member Serious Incident","Extra Safety Inspection","External Security Issue","Cross-Station Incident"]},
  {cat:"Seguridad",q:"¿Qué es GSOC?",a:"Global Security Operations Center",opts:["Global Security Operations Center","General Station Operations Control","Ground Safety Operations Check","Global Shipment Order Center"]},
  {cat:"Seguridad",q:"¿Qué significa OTR en seguridad?",a:"On The Road (incidentes vehiculares en ruta)",opts:["On The Road (incidentes vehiculares en ruta)","Over Time Report","Order Tracking Record","Outbound Transit Route"]},

  // === CATEGORÍA: Attainment ===
  {cat:"Attainment",q:"¿Qué es Attainment?",a:"% de paquetes que AMZL 'gana' para entregar vs. oportunidades ofrecidas",opts:["% de paquetes que AMZL 'gana' para entregar vs. oportunidades ofrecidas","% de paquetes entregados a tiempo","% de capacidad utilizada","% de conductores activos"]},
  {cat:"Attainment",q:"¿Cuáles son las 4 razones de pérdida de Attainment?",a:"Caps, Not feasible, PDD miss, More expensive",opts:["Caps, Not feasible, PDD miss, More expensive","Clima, Tráfico, Personal, Vehículos","Volumen, Calidad, Seguridad, Costo","DSP, Flex, Walker, Milkrun"]},
  {cat:"Attainment",q:"¿Qué significa 'Attainment Loss: Caps'?",a:"Pérdida porque la estación alcanzó su límite de capacidad",opts:["Pérdida porque la estación alcanzó su límite de capacidad","Pérdida por capital insuficiente","Pérdida por falta de gorras de uniforme","Pérdida por capacitación insuficiente"]},
  {cat:"Attainment",q:"¿Qué significa 'Attainment Loss: PDD miss'?",a:"Pérdida por no poder cumplir la fecha de entrega prometida",opts:["Pérdida por no poder cumplir la fecha de entrega prometida","Pérdida por paquetes dañados","Pérdida por personal ausente","Pérdida por problemas de sistema"]},
  {cat:"Attainment",q:"¿Qué significa 'Attainment Loss: More expensive'?",a:"AMZL resulta más caro que otra opción de envío",opts:["AMZL resulta más caro que otra opción de envío","El paquete es muy costoso","El DSP cobra de más","La ruta es muy larga"]},
  {cat:"Attainment",q:"¿Qué significa 'Attainment Loss: Not feasible'?",a:"No es factible la entrega por cobertura geográfica",opts:["No es factible la entrega por cobertura geográfica","No hay personal disponible","No hay vehículos","No hay sistema funcionando"]},
  {cat:"Attainment",q:"Si Attainment EU Hub DP = 77.01%, ¿qué significa?",a:"AMZL ganó el 77% de las oportunidades de entrega en EU Hub DP",opts:["AMZL ganó el 77% de las oportunidades de entrega en EU Hub DP","Se entregó el 77% de paquetes","El 77% de estaciones está activo","El 77% del forecast se cumplió"]},
  {cat:"Attainment",q:"¿Qué es el numerador (Num) en PANDA?",a:"Paquetes que AMZL ganó para entregar",opts:["Paquetes que AMZL ganó para entregar","Total de paquetes en la red","Paquetes entregados exitosamente","Paquetes devueltos"]},
  {cat:"Attainment",q:"¿Qué es el denominador (Den) en PANDA?",a:"Total de oportunidades ofrecidas a AMZL",opts:["Total de oportunidades ofrecidas a AMZL","Total de paquetes entregados","Total de estaciones activas","Total de conductores disponibles"]},

  // === CATEGORÍA: Operaciones ===
  {cat:"Operaciones",q:"¿Qué es un Milkrun?",a:"Ruta de recogida/entrega multi-parada entre estaciones",opts:["Ruta de recogida/entrega multi-parada entre estaciones","Ruta de entrega de lácteos","Turno nocturno","Ruta express premium"]},
  {cat:"Operaciones",q:"¿Qué es Linehaul?",a:"Transporte de larga distancia entre centros logísticos",opts:["Transporte de larga distancia entre centros logísticos","Última milla de entrega","Línea de producción en almacén","Ruta de un solo conductor"]},
  {cat:"Operaciones",q:"¿Qué es Last Mile?",a:"Último tramo de entrega desde la estación hasta la puerta del cliente",opts:["Último tramo de entrega desde la estación hasta la puerta del cliente","Última milla del linehaul","Último turno del día","Última revisión de calidad"]},
  {cat:"Operaciones",q:"¿Qué es Rescue/Rescued Volume?",a:"Volumen reasignado a otro conductor cuando uno no puede completar su ruta",opts:["Volumen reasignado a otro conductor cuando uno no puede completar su ruta","Paquetes rescatados de daño","Volumen recuperado de devoluciones","Paquetes encontrados perdidos"]},
  {cat:"Operaciones",q:"¿Qué son Sidelined Shipments?",a:"Paquetes retirados del flujo normal que no se entregarán ese día",opts:["Paquetes retirados del flujo normal que no se entregarán ese día","Paquetes en la línea lateral del almacén","Envíos secundarios","Paquetes de baja prioridad"]},
  {cat:"Operaciones",q:"¿Qué es Roster Compliance?",a:"Mide si los DSPs cumplen con el planning de turnos y rutas asignadas",opts:["Mide si los DSPs cumplen con el planning de turnos y rutas asignadas","Cumplimiento de uniformes","Lista de asistencia diaria","Registro de vehículos"]},
  {cat:"Operaciones",q:"¿Qué identifica un código como EHM5?",a:"Una estación específica dentro de la jerarquía de red",opts:["Una estación específica dentro de la jerarquía de red","Un tipo de paquete","Un código de error","Un turno de trabajo"]},
  {cat:"Operaciones",q:"¿Cuál es la jerarquía de una estación en ES?",a:"EU > SEU > ES > WW HDP > WW HDP ES > Estación",opts:["EU > SEU > ES > WW HDP > WW HDP ES > Estación","País > Ciudad > Calle","Global > Local","AMZL > DSP > Conductor"]},

  // === CATEGORÍA: Volume at Risk ===
  {cat:"Volume at Risk",q:"¿Qué es Volume at Risk - Linehaul?",a:"Volumen en riesgo por problemas de transporte de larga distancia",opts:["Volumen en riesgo por problemas de transporte de larga distancia","Volumen en camiones grandes","Paquetes pesados","Envíos internacionales"]},
  {cat:"Volume at Risk",q:"¿Qué es Volume at Risk - Ops Issue?",a:"Volumen en riesgo por problemas operativos",opts:["Volumen en riesgo por problemas operativos","Volumen de operaciones especiales","Paquetes de gran tamaño","Envíos con seguro"]},
  {cat:"Volume at Risk",q:"¿Qué es Volume To Be Rescued?",a:"Volumen que necesita ser reasignado/rescatado",opts:["Volumen que necesita ser reasignado/rescatado","Paquetes dañados por recuperar","Volumen de emergencia","Envíos perdidos"]},

  // === CATEGORÍA: Otros ===
  {cat:"Otros",q:"¿Qué significa ACES?",a:"Amazon Customer Excellence System",opts:["Amazon Customer Excellence System","Automated Control and Efficiency System","Advanced Carrier Evaluation Score","Amazon Compliance and Ethics Standard"]},
  {cat:"Otros",q:"¿Qué es WFS?",a:"Workforce Staffing (dotación de personal)",opts:["Workforce Staffing (dotación de personal)","Warehouse Fulfillment System","Weekly Financial Summary","Work Flow Scheduler"]},
  {cat:"Otros",q:"¿Qué es RCA?",a:"Root Cause Analysis (análisis de causa raíz)",opts:["Root Cause Analysis (análisis de causa raíz)","Regional Capacity Assessment","Route Compliance Audit","Real-time Customer Alert"]},
  {cat:"Otros",q:"¿Qué es un Flag en el DBR?",a:"Alerta generada cuando una métrica cruza su umbral/target",opts:["Alerta generada cuando una métrica cruza su umbral/target","Bandera de un país","Marcador de prioridad de paquete","Señal de fin de turno"]},
  {cat:"Otros",q:"¿Qué son las Concessions?",a:"Compensaciones al cliente (reembolso o reemplazo) por fallo en entrega",opts:["Compensaciones al cliente (reembolso o reemplazo) por fallo en entrega","Descuentos a DSPs","Permisos especiales","Concesiones de espacio"]},

  // === CATEGORÍA: Rol Diario ===
  {cat:"Rol",q:"¿Cuál es la primera tarea del día en el rol?",a:"Revisar las métricas del DBR cada mañana",opts:["Revisar las métricas del DBR cada mañana","Enviar emails a DSPs","Cargar paquetes","Revisar vehículos"]},
  {cat:"Rol",q:"¿Qué se hace cuando hay una desviación en métricas?",a:"Se escribe un RCA note (análisis de causa raíz)",opts:["Se escribe un RCA note (análisis de causa raíz)","Se cierra la estación","Se llama al cliente","Se despide al conductor"]},
  {cat:"Rol",q:"¿En qué horario se publican las notas matutinas?",a:"~8:18 - 9:07 AM",opts:["~8:18 - 9:07 AM","6:00 AM","12:00 PM","5:00 PM"]},
  {cat:"Rol",q:"¿Qué secciones del DBR requieren notas frecuentes?",a:"Volume SnOP y LMDX/Quality",opts:["Volume SnOP y LMDX/Quality","Safety y DEI","Finance y WFS","Launch y Expansion"]},

  // === CATEGORÍA: Métricas con valores reales ===
  {cat:"Métricas",q:"Si Delivered Shipments Hub DP = 184,499, ¿qué representa?",a:"Paquetes entregados por socios de entrega del Hub",opts:["Paquetes entregados por socios de entrega del Hub","Ingresos del día","Kilómetros recorridos","Horas trabajadas"]},
  {cat:"Métricas",q:"Si Attainment WON = 85.86%, ¿es bueno o malo?",a:"Es el % que AMZL ganó de oportunidades en la semana sobre la red",opts:["Es el % que AMZL ganó de oportunidades en la semana sobre la red","Es malo, debería ser 100%","Es el porcentaje de paquetes dañados","Es la tasa de ausentismo"]},
  {cat:"Métricas",q:"Si Positive Response Rate = 88.85%, ¿qué mide?",a:"Tasa de respuesta positiva del cliente sobre su experiencia",opts:["Tasa de respuesta positiva del cliente sobre su experiencia","% de conductores satisfechos","% de DSPs que respondieron encuesta","% de estaciones con buen clima laboral"]},
  {cat:"Métricas",q:"Si Last Mile (bps) Hub = 36, ¿qué significa?",a:"El coste de última milla es 36 puntos base (0.36%)",opts:["El coste de última milla es 36 puntos base (0.36%)","36 minutos promedio de entrega","36 paquetes por ruta","36 estaciones activas"]},
  {cat:"Métricas",q:"Si NOV DPMO Hub = 385, ¿qué indica?",a:"385 paquetes no cargados en van por cada millón de oportunidades",opts:["385 paquetes no cargados en van por cada millón de oportunidades","385 vans disponibles","385 defectos totales del día","385 conductores activos"]},

  // === CATEGORÍA: Finance ===
  {cat:"Finance",q:"¿Qué significa CPS en Finance?",a:"Cost Per Shipment (coste por paquete enviado)",opts:["Cost Per Shipment (coste por paquete enviado)","Capacity Planning System","Central Processing Station","Customer Priority Score"]},
  {cat:"Finance",q:"¿Qué es HubDP Store Cost?",a:"Coste total de operación del Hub para entregas con Delivery Partners",opts:["Coste total de operación del Hub para entregas con Delivery Partners","Coste de almacenamiento","Precio de venta de productos","Coste de alquiler del edificio"]},
  {cat:"Finance",q:"¿Qué mide Hub Store CPS - HubDP?",a:"Coste por paquete de la operación del Hub con DPs",opts:["Coste por paquete de la operación del Hub con DPs","Capacidad por estación","Clientes por segmento","Conductores por shift"]},
  {cat:"Finance",q:"¿Qué es Milkrun CPS?",a:"Coste por paquete de las rutas milkrun",opts:["Coste por paquete de las rutas milkrun","Cantidad de milkruns por semana","Capacidad máxima de un milkrun","Coste del vehículo milkrun"]},
  {cat:"Finance",q:"¿Qué incluye Other Fixed & Overhead CPS?",a:"Costes fijos y generales por paquete (alquiler, admin, etc.)",opts:["Costes fijos y generales por paquete (alquiler, admin, etc.)","Costes de horas extra","Costes de paquetes dañados","Costes de devoluciones"]},
  {cat:"Finance",q:"¿Qué es Total CPS - HubDP?",a:"Suma de todos los costes por paquete (Store + Milkrun + Fixed)",opts:["Suma de todos los costes por paquete (Store + Milkrun + Fixed)","Total de paquetes enviados","Total de conductores activos","Total de estaciones operativas"]},
  {cat:"Finance",q:"¿Qué es Benchmark CPS - Urban?",a:"Coste de referencia por paquete en zonas urbanas para comparar",opts:["Coste de referencia por paquete en zonas urbanas para comparar","Mejor CPS histórico","CPS del competidor","CPS objetivo del año"]},
  {cat:"Finance",q:"¿Qué indica Delta vs Benchmark CPS?",a:"Diferencia entre el CPS real del Hub y el benchmark urbano",opts:["Diferencia entre el CPS real del Hub y el benchmark urbano","Variación del volumen","Cambio en el número de rutas","Diferencia de personal"]},
  {cat:"Finance",q:"Si Delta vs Benchmark CPS es positivo (ej: 0.69), ¿qué significa?",a:"El Hub es más barato que el benchmark (ahorra $0.69 por paquete)",opts:["El Hub es más barato que el benchmark (ahorra $0.69 por paquete)","El Hub es más caro que el benchmark","Hay un error en el cálculo","El volumen subió 0.69%"]},
  {cat:"Finance",q:"¿Qué es Delta vs Benchmark Costs (SL)?",a:"Ahorro total en dólares vs. benchmark a nivel de Service Level",opts:["Ahorro total en dólares vs. benchmark a nivel de Service Level","Coste de penalización","Presupuesto restante","Inversión en nuevas estaciones"]},
  {cat:"Finance",q:"Si Total CPS = $1.56 y Benchmark = $2.25, ¿el Hub es eficiente?",a:"Sí, el Hub cuesta $0.69 menos por paquete que el benchmark",opts:["Sí, el Hub cuesta $0.69 menos por paquete que el benchmark","No, debería ser $0","No se puede determinar","Solo si el volumen es alto"]},
  // === CATEGORÍA: ACES In Station ===
  {cat:"ACES Station",q:"¿Qué son Ageing Shipments?",a:"Paquetes atascados en la estación que no se han entregado en X días",opts:["Paquetes atascados en la estación que no se han entregado en X días","Paquetes antiguos del inventario","Paquetes con fecha de caducidad","Envíos de clientes mayores"]},
  {cat:"ACES Station",q:"¿Por qué se miden Ageing Shipments en tramos (3, 4, 5, 6+ días)?",a:"Para identificar la gravedad: más días = más urgente resolver",opts:["Para identificar la gravedad: más días = más urgente resolver","Por requisito legal","Para calcular el coste de almacenamiento","Para asignar prioridad de entrega"]},
  {cat:"ACES Station",q:"Si Ageing 6+ Days = 8,435, ¿qué indica?",a:"8,435 paquetes llevan más de 6 días sin entregarse (crítico)",opts:["8,435 paquetes llevan más de 6 días sin entregarse (crítico)","8,435 paquetes se entregaron hace 6 días","8,435 estaciones tienen 6+ días de operación","8,435 conductores llevan 6+ días trabajando"]},
  {cat:"ACES Station",q:"¿Qué significa FPY DPMO (WW Scorecard)?",a:"First Pass Yield - defectos de calidad al primer intento, por millón",opts:["First Pass Yield - defectos de calidad al primer intento, por millón","Full Package Yield","Final Processing Year","Freight Priority Yield"]},
  {cat:"ACES Station",q:"¿Qué mide On Time Dispatch % - DSP?",a:"% de rutas DSP que salieron a tiempo de la estación",opts:["% de rutas DSP que salieron a tiempo de la estación","% de paquetes entregados a tiempo","% de conductores puntuales","% de camiones que llegaron a tiempo"]},
  {cat:"ACES Station",q:"Si On Time Dispatch = 98.13%, ¿qué significa?",a:"El 98.13% de las rutas DSP salieron de la estación en horario",opts:["El 98.13% de las rutas DSP salieron de la estación en horario","El 98.13% de paquetes se entregó","El 98.13% de personal asistió","El 98.13% de capacidad se usó"]},
  {cat:"ACES Station",q:"¿Qué es ASL Utilisation %?",a:"Available Shift Labor - % de uso del personal disponible por turno",opts:["Available Shift Labor - % de uso del personal disponible por turno","Average Station Load","Automated Sort Line utilization","Assigned Shipment Level"]},
  {cat:"ACES Station",q:"¿Qué es ADTA Utilisation %?",a:"Available Delivery Time Allocation - % uso del tiempo de entrega disponible",opts:["Available Delivery Time Allocation - % uso del tiempo de entrega disponible","Average Daily Transport Activity","Automated Dispatch Time Analysis","Annual Delivery Target Achievement"]},
  {cat:"ACES Station",q:"Si ADTA Utilisation = 100.30%, ¿qué indica?",a:"Se está usando más tiempo del asignado (sobrecarga ligera)",opts:["Se está usando más tiempo del asignado (sobrecarga ligera)","Todo funciona perfectamente","Hay un 0.30% de error","Sobran recursos de tiempo"]},
  {cat:"ACES Station",q:"Si ASL Utilisation = 78.05%, ¿es bueno o malo?",a:"Hay margen: solo se usa el 78% del personal disponible",opts:["Hay margen: solo se usa el 78% del personal disponible","Es malo, debería ser 100%","Es excelente, sobra personal","No se puede determinar sin más contexto"]},

  // === CATEGORÍA: ACES On Road ===
  {cat:"ACES Road",q:"¿Qué mide Carbon Emission Reduction vs Van?",a:"Reducción de emisiones CO2 al usar métodos alternativos vs. furgoneta",opts:["Reducción de emisiones CO2 al usar métodos alternativos vs. furgoneta","Consumo de combustible por van","Número de vans eléctricas","Coste del carbono por ruta"]},
  {cat:"ACES Road",q:"¿Qué mide Delivered by Milkrun %?",a:"% de paquetes entregados mediante rutas milkrun vs. total",opts:["% de paquetes entregados mediante rutas milkrun vs. total","% de milkruns completados","% de leche entregada","% de rutas multi-parada"]},
  {cat:"ACES Road",q:"Si Delivered by Milkrun = 1.88%, ¿qué indica?",a:"Solo el 1.88% del volumen se entrega por milkrun (adopción baja)",opts:["Solo el 1.88% del volumen se entrega por milkrun (adopción baja)","El 1.88% de milkruns falló","Se ahorra 1.88% en costes","1.88% de conductores usan milkrun"]},
  {cat:"ACES Road",q:"¿Qué es SPR (Milkrun SPR)?",a:"Shipments Per Route - paquetes entregados por cada ruta milkrun",opts:["Shipments Per Route - paquetes entregados por cada ruta milkrun","Speed Per Route","Station Performance Rating","Standard Processing Rate"]},
  {cat:"ACES Road",q:"Si Milkrun SPR = 403.65, ¿qué significa?",a:"Cada ruta milkrun entrega en promedio 403 paquetes (alta eficiencia)",opts:["Cada ruta milkrun entrega en promedio 403 paquetes (alta eficiencia)","403 milkruns activos","403 minutos por ruta","403 km por ruta"]},
  {cat:"ACES Road",q:"¿Qué mide Average Daily Volume Per Hub?",a:"Promedio de paquetes procesados por hub al día",opts:["Promedio de paquetes procesados por hub al día","Promedio de conductores por hub","Promedio de horas operativas","Promedio de rutas por hub"]},
  {cat:"ACES Road",q:"¿Qué es Total Number of Milkruns (Harmony)?",a:"Cantidad total de rutas milkrun activas según el sistema Harmony",opts:["Cantidad total de rutas milkrun activas según el sistema Harmony","Milkruns históricos totales","Milkruns cancelados","Milkruns planificados para el futuro"]},

  // === CATEGORÍA: WFS (Workforce Staffing) ===
  {cat:"WFS",q:"¿Qué es D1S (Day One Starts)?",a:"Número de nuevos empleados que empiezan su primer día de trabajo",opts:["Número de nuevos empleados que empiezan su primer día de trabajo","Día 1 de una estación nueva","Primer envío del día","Primera ruta despachada"]},
  {cat:"WFS",q:"Si Weekly D1S = 62, ¿qué significa?",a:"62 personas comenzaron a trabajar esta semana",opts:["62 personas comenzaron a trabajar esta semana","62 rutas nuevas creadas","62 estaciones abiertas","62 DSPs contratados"]},
  {cat:"WFS",q:"¿Qué es Locked Labor Order (LO)?",a:"Pedido de personal confirmado/bloqueado sin cambios de último momento",opts:["Pedido de personal confirmado/bloqueado sin cambios de último momento","Orden de bloqueo de estación","Pedido de candados para lockers","Orden laboral legal"]},
  {cat:"WFS",q:"¿Qué significa RLC (Red Level Changes)?",a:"Cambios de último momento en los pedidos de personal (urgentes)",opts:["Cambios de último momento en los pedidos de personal (urgentes)","Reducciones de nivel de capacidad","Reportes de nivel crítico","Rotación laboral controlada"]},
  {cat:"WFS",q:"¿Qué es Labor Order incl. Red Level Changes?",a:"Pedido total de personal incluyendo ajustes urgentes de última hora",opts:["Pedido total de personal incluyendo ajustes urgentes de última hora","Orden de trabajo con nivel rojo de riesgo","Personal en alerta roja","Pedido cancelado por emergencia"]},
  {cat:"WFS",q:"¿Qué mide New Hire Fill Rate (vs Locked LO)?",a:"% de posiciones cubiertas vs. las que se pidieron originalmente",opts:["% de posiciones cubiertas vs. las que se pidieron originalmente","% de formularios completados","% de capacitación terminada","% de uniformes entregados"]},
  {cat:"WFS",q:"Si Fill Rate vs Locked LO = 101.64%, ¿qué indica?",a:"Se contrató más gente de la pedida originalmente (101% cubierto)",opts:["Se contrató más gente de la pedida originalmente (101% cubierto)","Hay un error en el sistema","Sobra un 1.64% de personal","El 1.64% renunció"]},
  {cat:"WFS",q:"Si Fill Rate vs LO+RLC = 79.49%, ¿qué indica?",a:"Solo se cubrió el 79% del personal total necesario (incluyendo urgentes)",opts:["Solo se cubrió el 79% del personal total necesario (incluyendo urgentes)","El 79% del personal es nuevo","El 79% completó su turno","El 79% pasó la capacitación"]},
  {cat:"WFS",q:"¿Por qué hay dos Fill Rates (vs LO y vs LO+RLC)?",a:"Uno mide contra el plan original, otro contra el plan + cambios urgentes",opts:["Uno mide contra el plan original, otro contra el plan + cambios urgentes","Uno es semanal y otro mensual","Uno es de DSPs y otro de Flex","Uno es de día y otro de noche"]},

  // === CATEGORÍA: Attainment Avanzado (WtD) ===
  {cat:"Attainment",q:"¿Qué mide Attainment - Caps Losses % WtD?",a:"% acumulado semanal de oportunidades perdidas por límite de capacidad",opts:["% acumulado semanal de oportunidades perdidas por límite de capacidad","% de estaciones con caps","% de paquetes dañados","% de rutas canceladas"]},
  {cat:"Attainment",q:"Si Caps Losses WtD = 5.75%, ¿qué significa?",a:"En la semana, el 5.75% de oportunidades se perdió por falta de capacidad",opts:["En la semana, el 5.75% de oportunidades se perdió por falta de capacidad","El 5.75% de estaciones cerró","El 5.75% de paquetes se dañó","El 5.75% de conductores faltó"]},
  {cat:"Attainment",q:"¿Qué mide Attainment - Slow Connections % WtD?",a:"% semanal de pérdida por conexiones lentas entre nodos de la red",opts:["% semanal de pérdida por conexiones lentas entre nodos de la red","% de internet lento en estaciones","% de conductores lentos","% de sistemas caídos"]},
  {cat:"Attainment",q:"¿Qué mide Attainment - Cost Losses % WtD?",a:"% semanal de oportunidades perdidas porque AMZL era más caro",opts:["% semanal de oportunidades perdidas porque AMZL era más caro","% del presupuesto gastado","% de sobrecostes operativos","% de multas pagadas"]},
  {cat:"Attainment",q:"Si Losses due to Caps = 525,846, ¿qué representa?",a:"Paquetes que no se pudieron aceptar por falta de capacidad en estaciones",opts:["Paquetes que no se pudieron aceptar por falta de capacidad en estaciones","Dinero perdido en dólares","Minutos perdidos","Conductores sin ruta"]},
  {cat:"Attainment",q:"¿Qué es CO - Roster Compliance W0/W1?",a:"Cumplimiento del roster de DSPs en semana actual (W0) y siguiente (W1)",opts:["Cumplimiento del roster de DSPs en semana actual (W0) y siguiente (W1)","Compliance Officer semanal","Control de calidad semanal","Conteo de operaciones"]},

  // === CATEGORÍA: LMDX Avanzado ===
  {cat:"LMDX",q:"¿Qué son Conceded Units AMZL Hub?",a:"Unidades con concesión (compensación) otorgada al cliente por fallo",opts:["Unidades con concesión (compensación) otorgada al cliente por fallo","Unidades cedidas a otro carrier","Paquetes transferidos entre hubs","Unidades devueltas al vendedor"]},
  {cat:"LMDX",q:"¿Qué mide Lost DPMO - Hub?",a:"Paquetes perdidos por millón de oportunidades en el Hub",opts:["Paquetes perdidos por millón de oportunidades en el Hub","Dinero perdido por millón","Tiempo perdido por operación","Conductores perdidos por mes"]},
  {cat:"LMDX",q:"Si Lost DPMO Hub = 342, ¿es grave?",a:"342 paquetes perdidos por millón - relativamente bajo pero se monitorea",opts:["342 paquetes perdidos por millón - relativamente bajo pero se monitorea","Es crítico, hay que cerrar el hub","Es normal, no requiere acción","No se puede evaluar sin contexto"]},
  {cat:"LMDX",q:"¿Qué es Last Mile (bps) [Int PDD - DS] Hub DP?",a:"Coste de última milla en BPS para entregas con PDD internacional",opts:["Coste de última milla en BPS para entregas con PDD internacional","Puntos base de la primera milla","Coste del linehaul internacional","Benchmark de entregas domésticas"]},
  {cat:"LMDX",q:"Si Last Mile bps Int PDD = 84 vs. Last Mile bps Hub = 36, ¿qué indica?",a:"Las entregas internacionales cuestan más del doble en última milla",opts:["Las entregas internacionales cuestan más del doble en última milla","Hay un error en los datos","El hub internacional es más eficiente","Son métricas no comparables"]},

  // === CATEGORÍA: Volume at Risk Avanzado ===
  {cat:"Volume at Risk",q:"¿Qué diferencia hay entre Sidelined Shipments y Sideline Out Actuals?",a:"Sidelined = planificados a retirar, Sideline Out Actuals = realmente retirados",opts:["Sidelined = planificados a retirar, Sideline Out Actuals = realmente retirados","Son lo mismo con diferente nombre","Uno es de entrada y otro de salida","Uno es manual y otro automático"]},
  {cat:"Volume at Risk",q:"Si Sidelined = 44,633 pero Sideline Out = 46,834, ¿qué pasó?",a:"Se retiraron más paquetes de los planificados (2,201 extra)",opts:["Se retiraron más paquetes de los planificados (2,201 extra)","Hay un error de conteo","Se recuperaron paquetes","Los números son normales"]},
];
