const SCENARIOS = [
{title:"Cap Utilization al 99.2%",
 context:"Son las 8:30 AM. El DBR muestra que la estación EHM4 tiene Cap Utilization al 99.2% para hoy (D0). El forecast de mañana indica +3% de volumen vs. hoy.",
 metric:"Cap Util: 99.2% | Fcst ND: +3%",
 question:"¿Qué acción priorizas?",
 options:["Redirigir volumen a estaciones cercanas con capacidad","Esperar a ver si el volumen real baja","Pedir más personal para mañana","Contactar al DSP para añadir rutas"],
 correct:0,
 explain:"Con 99.2% hoy y +3% mañana, la estación se saturará. La acción inmediata es redirigir volumen (sideline preventivo o rerouting) a estaciones con margen. Pedir personal no resuelve el problema de espacio físico."},
{title:"Attainment Loss por Caps = 9.89%",
 context:"El attainment de Hub DP está en 77.01%. La mayor pérdida es por Caps (9.89%), seguida de PDD miss (6.69%). Hay 154 estaciones con Cap Util > 98%.",
 metric:"Attainment: 77.01% | Caps Loss: 9.89% | Stations >98%: 154",
 question:"¿Cuál es la causa raíz más probable y qué escribes en el RCA?",
 options:["Volumen real superó el forecast → pedir revisión de Fcst y expandir caps en top stations","Los DSPs no cumplieron el roster → escalar a DSP management","Hubo un problema de linehaul → revisar con transporte","El sistema PANDA tiene un error → abrir ticket IT"],
 correct:0,
 explain:"154 estaciones saturadas + 9.89% caps loss indica que el volumen superó la capacidad planificada. El RCA debe señalar la desviación vs forecast y la acción es expandir capacidad en las estaciones más afectadas."},
{title:"First Day Delivery baja a 96.5%",
 context:"El target de First Day Delivery Success es 98.5%. Hoy marca 96.5%, una caída de 2 puntos. El Volume at Risk - Linehaul subió a 85,000 (normalmente es ~50,000).",
 metric:"FDDS: 96.5% (target 98.5%) | VaR Linehaul: 85K",
 question:"¿Qué conexión haces y qué acción tomas?",
 options:["Linehaul tardío causó que paquetes no llegaran a tiempo → escalar a transporte + flag en DBR","Los conductores fueron lentos → revisar SPR","Las stores no abrieron → revisar rostering","El forecast fue incorrecto → ajustar SnOP"],
 correct:0,
 explain:"La correlación es clara: VaR Linehaul subió 70% → paquetes llegaron tarde a las estaciones → no se pudieron entregar en su PDD. Acción: escalar a transporte, documentar en DBR con flag y crear action item."},
{title:"NOV DPMO sube a 850",
 context:"El NOV DPMO Hub normalmente está en ~385. Hoy marca 850. On Time Dispatch bajó de 98% a 94%. La estación DCT4 reporta problemas con el escáner.",
 metric:"NOV DPMO: 850 (normal: 385) | OTD: 94% | DCT4: escáner averiado",
 question:"¿Qué está pasando y qué haces?",
 options:["El escáner averiado causa que paquetes no se escaneen al cargar → ticket urgente de mantenimiento + flag","Hay exceso de volumen → redirigir paquetes","Los DSPs llegaron tarde → penalizar roster","Es un error de datos → ignorar hasta mañana"],
 correct:0,
 explain:"Escáner averiado → paquetes no se registran como cargados (NOV) → retraso en dispatch (OTD baja). Acción inmediata: ticket de mantenimiento urgente, flag en DBR, y plan B manual mientras se repara."},
{title:"Fill Rate vs LO+RLC = 65%",
 context:"WFS reporta que solo se cubrió el 65% del personal necesario esta semana (LO+RLC). La semana que viene es Prime Week con +40% de volumen esperado.",
 metric:"Fill Rate: 65% | Next week: Prime (+40% vol)",
 question:"¿Qué riesgo identificas y qué acción tomas?",
 options:["Sin personal suficiente no habrá capacidad para Prime → escalar a WFS + plan de contingencia con DSPs extras","Es normal, se cubrirá la próxima semana","Reducir el forecast de Prime para ajustar","Pedir a los DSPs que trabajen horas extra"],
 correct:0,
 explain:"65% fill rate + Prime en 7 días = crisis inminente. Sin personal, las estaciones no pueden procesar el +40% de volumen → sidelines masivos, caps loss, attainment desplomado. Hay que escalar YA."},
{title:"Concession DPMO sube a 12,000",
 context:"El Concession DPMO Hub normalmente está en ~7,000. Esta semana subió a 12,000. Al revisar, ves que Ageing Shipments 6+ Days pasó de 8,000 a 15,000.",
 metric:"Concession DPMO: 12K (normal: 7K) | Ageing 6+: 15K",
 question:"¿Cuál es la conexión y qué priorizas?",
 options:["Paquetes envejecidos generan concesiones automáticas → plan de limpieza de ageing + RCA por categoría","Los clientes están más exigentes → no se puede hacer nada","Hay un bug en el sistema de concesiones → ticket IT","Los DSPs están dañando paquetes → auditoría"],
 correct:0,
 explain:"Ageing 6+ duplicado → esos paquetes ya superaron el SLA → concesiones automáticas. La prioridad es limpiar el backlog de ageing (forzar entregas o sideline definitivo) y hacer RCA de por qué se acumularon."},
{title:"Milkrun SPR cae a 180",
 context:"El Milkrun SPR normalmente es ~400. Esta semana cayó a 180. El número de milkruns activos no cambió. El volumen total tampoco bajó significativamente.",
 metric:"Milkrun SPR: 180 (normal: 400) | Milkruns activos: igual | Volumen: estable",
 question:"¿Qué está pasando?",
 options:["Las rutas milkrun se están asignando con menos volumen del óptimo → revisar planificación de rutas en Harmony","Los conductores milkrun son nuevos y lentos","Hay stores cerradas en las rutas → revisar rostering","El sistema Harmony tiene un error"],
 correct:0,
 explain:"Mismo número de rutas + mismo volumen total pero SPR a la mitad = el volumen se está distribuyendo mal entre rutas. Hay que revisar la planificación en Harmony para optimizar la asignación."},
{title:"Attainment Loss: More Expensive sube a 5%",
 context:"Normalmente la pérdida por 'More Expensive' es ~2.5%. Esta semana subió a 5%. El Total CPS del Hub subió de $1.56 a $1.95 por un incremento en costes de transporte.",
 metric:"Cost Loss: 5% (normal: 2.5%) | CPS: $1.95 (normal: $1.56)",
 question:"¿Qué significa y qué recomiendas?",
 options:["El Hub se volvió más caro que alternativas → investigar causa del incremento en CPS y negociar con transporte","Hay que subir precios al cliente","Es temporal por temporada alta → no hacer nada","Cerrar rutas no rentables inmediatamente"],
 correct:0,
 explain:"CPS subió 25% → PANDA detecta que AMZL es más caro → asigna paquetes a otros carriers → perdemos attainment. Hay que investigar qué componente del CPS subió (¿transporte? ¿personal?) y actuar sobre esa causa."},
];
